### ISSUE TITLE
Error converting ulid lightener_context to bytes: ULID must be a 26 character string: lightener_context

### ISSUE THREAD

**Issue by MacrosorcH** [fredck/lightener#1]
First of all, thanks for the great work!

Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1

Hundreds of errors like the following are logged:

2023-05-02 20:21:17.542 ERROR (Recorder) [homeassistant.components.recorder.models.context] Error converting ulid lightener_context to bytes: ULID must be a 26 character string: lightener_context
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/recorder/models/context.py", line 19, in ulid_to_bytes_or_none
return ulid_to_bytes(ulid)
File "src/ulid_transform/_ulid_impl.pyx", line 23, in ulid_transform._ulid_impl._ulid_to_bytes
ValueError: ULID must be a 26 character string: lightener_context

**Comment by fredck** [comment]
Thanks for the report. I could confirm the issue although apparently everything seems to work.

**Comment by fredck** [comment]
Fixed with c0afc1c3c9fff2c334d12f714379b7b41ef3caba.
